### ISSUE TITLE
SHACL W3C Compliance Tests

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j-storage#101]
W3C have developed a bunch of compliance tests for SHACL. These should be included our SHACL tests. 

Most will naturally fail at the moment since we only support a small subset of SHACL. However, this shouldn't fail the build.

**Comment by jeenbroekstra** [comment]
@hmottestad can you give me a link to where you grabbed this test suite from? Then I'll log a CQ for adding this content.

**Comment by hmottestad** [comment]
Thanks. 

https://github.com/w3c/data-shapes/tree/gh-pages/data-shapes-test-suite/tests

**Comment by jeenbroekstra** [comment]
This issue was moved to eclipse/rdf4j#1117
