### ISSUE TITLE
Error in GeoSPARQL function evaluation

### ISSUE THREAD

**Issue by tioannid** [eclipse/rdf4j-storage#108]
Hi I am using the latest version RDF4J 2.4.0-M3 and I am trying to execute the following query:

`PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX lgd: <http://data.linkedeodata.eu/ontology#>
 SELECT ?s1 ?o1 WHERE {
 ?s1 geo:asWKT ?o1 .
  FILTER(geof:sfIntersects(?o1, "POINT (-3.9468805 51.618055)"^^<http://www.opengis.net/ont/geosparql#wktLiteral>)).
}`

The expected result is the following:

`s1                                           o1
http://data.linkedeodata.eu/osm/wales/transport/Geometry/16202470   MULTIPOLYGON (((-3.9469452 51.6180887, -3.9467408 51.6183097, -3.9464539 51.6182493, -3.9457195 51.6174283, -3.9459201 51.617293, -3.9460423 51.6171659, -3.9462114 51.6174525, -3.9463139 51.6175729, -3.9466882 51.6179044, -3.9469452 51.6180887)))
`
The same dataset has been loaded with GraphDB v8.5 and RDF4J 2.4.0-M3, the repositories verified.

The java error I received is the following: java error executing query of RDF4J repo

I have used the correct dependency for the BOM and rdf4j-queryalgebra-geosparql.

My dataset contains POINT, POLYGON, MULTIPOLYGON.

Any help will be appreciated.
![image](https://user-images.githubusercontent.com/15914587/45586066-dc2ae900-b8f8-11e8-9f9a-12bea0763982.png)

**Comment by jeenbroekstra** [comment]
It looks like there is a problem in the maven dependency setup. When importing milestone 3 via maven dependencies, it somehow resolves the spatial4j dependency to version 0.6, despite rdf4j-queryalgebra-geosparql _explicitly_ setting the dependency version to 0.7.

We'll look into why that happens and try and fix it before the final release. In the mean time, a workaround for you would be include the following dependency in your own project pom:

```
      <dependency>
        <groupId>org.locationtech.spatial4j</groupId>
        <artifactId>spatial4j</artifactId>
        <version>0.7</version>
      </dependency>
```

**Comment by tioannid** [comment]
Thank you very much Jeen.

It worked!

**Comment by jeenbroekstra** [comment]
I'll keep this open to make sure we don't forget to fix the underlying issue.

**Comment by jeenbroekstra** [comment]
I have verified that this problem no longer occurs with the latest 2.4 snapshots.
