### ISSUE TITLE
MemoryOverflowModel should use max heap size instead of currrently allocated RAM

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j-storage#43]
The `MemoryOverflowModel` currently uses `Runtime.totalMemory()` to estimate memory consumption for determining whether to sync to disk. However, this method only returns the total _currently allocated_ memory, which is not necessarily the maximum amount of memory available for the JVM. This results in the model syncing to disk earlier than required, which has a large performance penalty. As part of a fix we should instead use `Runtime.maxMemory` which returns the maximum heap size, and do our treshold estimates from there.

**Comment by hmottestad** [comment]
@jeenbroekstra I ran into this issue now on my #44, where the number of transactions created by the MemoryOverflowModel was so large that reducing the amount of bytes written to the transaction status file impacted the performance dramatically.

I have, however, found something you should look into. When I add System.gc() before the memory checks in MemoryOverflowModel, org.eclipse.rdf4j.sail.SailConcurrencyTest#testConcurrentAddLargeTxn goes from 84 seconds to 22 seconds. Nothing else changed!

```
	private synchronized void checkMemoryOverflow() {
		if (disk == null) {
			int size = size();
			if (size >= LARGE_BLOCK && size % LARGE_BLOCK == 0) {
				System.gc(); // Hint to JVM to do GC before we measure memory pressure
				long totalMemory = RUNTIME.totalMemory();
				long freeMemory = RUNTIME.freeMemory();
				long used = totalMemory - freeMemory;
				if (baseline > 0) {
					long blockSize = used - baseline;
					if (blockSize > maxBlockSize) {
						maxBlockSize = blockSize;
					}
					if (freeMemory < size / LARGE_BLOCK * maxBlockSize) {
						// may not be enough free memory for another
						overflowToDisk();
					}
				}
				baseline = used;
			}
		}
	}

```

**Comment by hmottestad** [comment]
Btw. After some testing, this seems to be the correct way of measuring memory pressure in java:

```
long used = RUNTIME.totalMemory() - RUNTIME.freeMemory();
long freeMemory = RUNTIME.maxMemory()-used;
```

**Comment by hmottestad** [comment]
Seems that the latter is the better fix.

**Comment by jeenbroekstra** [comment]
@hmottestad that a call to `System.gc()` should make such a difference is a bit shocking. I've just put up a PR that doesn't use that trick, but does use Runtime.maxMemory. Can you verify if the performance improves as much with this change in place as well?

**Comment by hmottestad** [comment]
For fun: this merge has reduced the time that Travis takes to run all our tests from ~30 min to 20~. Which is awesome.
