### ISSUE TITLE
Upgrade Lucene, Elasticsearch and Solr Dependency to Lucene 6.x

### ISSUE THREAD

**Issue by aschwarte10** [eclipse/rdf4j-storage#71]
In the current RDF4J release Lucene 5.x is used as a basis for keyword search and search indexes. This version of lucene is outdated and declared Branch End-Of-Live.

The same holds for the elasticsearch sail (version 2.x) and solr.

For security reasons it is highly recommended to upgrade these 3rd party dependencies.

It is to be evaluated whether  the upgrade will be done in two steps or in a single step, i..e whether to skip a major lucene version (6.x) or not.

As a first step the codebase is to be updated to the following versions

Lucene (5.5.4 -> 6.6.4)
Elastic Search (2.4.6 -> 5.6.9)
Solr (5.5.4 -> 6.6.4)

Later (or in a next task) it may be decided to do the step to a lucene 7.x based dependency

**Comment by barthanssens** [comment]
@jeenbroekstra  as this is an upgrade to a new major versions, does this require a CQ from Eclipse ?

**Comment by jeenbroekstra** [comment]
@barthanssens yes, it does. In fact _every_ version update of a dependency, even if it's only a patch, requires that. I'll log the CQs ASAP.

**Comment by barthanssens** [comment]
@jeenbroekstra ow, patch releases as well ? Strange, I was under the impression that patch (or service releases) didn't require a CQ (https://wiki.eclipse.org/Development_Resources/Contribution_Questionnaire#Third_Party_Libraries). 
Good to know, since I was planning to upgrade a few other libraries as well (e.g. slf4j, jackson etc are a few patch releases behind) in other tickets

**Comment by jeenbroekstra** [comment]
@barthanssens er, good find. That's actually the way I read that too. Perhaps they've loosened their policy (or else I've just misunderstood, definitely possible). I will doublecheck but you might be correct that we don't need a CQ for patch-level upgrades.

**Comment by jeenbroekstra** [comment]
Aw, I had forgotten what a dependency hell these three projects are. I need to log CQs for _every_ _single_ upgraded jar file, including any transitive dependencies of these projects (though fortunately, not for optional dependencies, so solr-core and its transitive deps can be ignored). 

As spatial4j is a LocationTech project and therefore part of Eclipse, no CQ is needed for that upgrade.

CQs for lucene/solr dependencies:

lucene-core: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16500
lucene-queries: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16501
lucene-highlighter: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16502
lucene-analyzers-common: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16503
lucene-join: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16504
lucene-memory: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16505
lucene-queryparser: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16506
lucene-sandbox: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16507
lucene-spatial: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16508
lucene-spatial-extras: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16509
lucene-misc: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16510
lucene-spatial3d: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16511
solr-solrj: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16512
commons-math3: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16525

I may have overlooked some further transitive dependencies. 

Will do the elasticsearch CQs later, I want to take a look at our poms and see if we can reduce the scope somewhat, I get the feeling we have a lot of dependencies in there we don't really need.

**Comment by jeenbroekstra** [comment]
@aschwarte10 do you think we could tweak our elasticsearch support in such a way that we don't actually distribute any of its jars ourselves? It would save us an awful lot of bookkeeping if we could just say "here's our elasticsearch client, if you want to actually use it, you'll have to download/install elasticsearch yourself".

**Comment by aschwarte10** [comment]
@jeenbroekstra do you already have something in mind to avoid the dependencies? I would also be very much in favor of this as elasticsearch is really a mess with all its dependencies. 

Currently the elasticsearch API is heavily referenced in the implementation, i.e. currently it is a strong compile and runtime dependency. I am not familiar with elasticsearch, so I am not sure whether we can simply use a different approach here. If I understand elasticsearch correctly, in the newer versions it uses a REST based client Maybe this can help us somehow?

See also https://www.elastic.co/blog/state-of-the-official-elasticsearch-java-clients for a discussion, especially the section of the dependencies is interesting

**Comment by jeenbroekstra** [comment]
@aschwarte10 I think to achieve we need to do two things:

1. mark the elasticsearch dependency in the pom file as optional (similar to what we do for the `solr-core` dependency in the solr sail)
2. make sure the assembly scripts for the sdk and onejar filter out these dependencies.

If we can set things up this way we can settle for just logging a "works-with" CQ for the main elasticsearch client library, without having to log CQs for all its transitive dependencies as well.

**Comment by jeenbroekstra** [comment]
@aschwarte10 I was going to push a fix to the poms to your branch but I don't seem to have write access to your fork :)

**Comment by jeenbroekstra** [comment]
@aschwarte10 I've pushed a change to the poms to your branch, have a look, it shows what I have in mind.

**Comment by jeenbroekstra** [comment]
Just to make it clear: any maven users can very easily still pull in everything they need to make this works, simply by adding the optional dependency as an _actual_ dependency to their own project pom. 

For users of the Workbench/Server it's a little more tricky (basically downloading Elasticsearch zip file and copying all the jars in its lib dir to the Server's webapp/lib dir), though I am not even sure we currently offer the Elasticsearch Sail as one of the repository config options there.

**Comment by aschwarte10** [comment]
@jeenbroekstra I pushed two further commits: one about the remaining TODO in the elastic search API migration and the other one about adding a workaround to get the elastic search compliance test run.

Notes: I had to switch to lucene 6.6.1 (latest is 6.6.4) as Elasticsearch has an exact version check (i.e. an assertion). Also I needed to workaround the JarHell test (could not get it running otherwise with the current dependencies). If you find a solution without this workaround, feel free to provide a change. The test checks for different versions of Jars being on the classpath.

**Comment by jeenbroekstra** [comment]
@barthanssens thanks for that. I'm happy to go with this. A little additional annoyance for some of our users, but if we document the steps needed to get ElasticSearch going I'm fine with this. Also makes the download somewhat lighter as we don't have to bundle all these additional jars. Living in Australia has made me a little more conscious of the cost of big downloads :) 

I'll still need to log 'work-with' CQ for the elasticsearch transport library, as well as the lucene and elasticsearch test libraries included in the compliance tests, but that's far more doable and also easier for the IP team to process.

**Comment by aschwarte10** [comment]
I did an evaluation of the updated lucene sail (locally built onejar and the updated lucene libs) in our application. 
Scenario: run the new version (2.4 SNAPSHOT) with an existing lucene 5.x index.

First thing I got when accessing the index (without re-indexing) is the following message

java.lang.IllegalArgumentException: Could not load codec 'Lucene50'.  Did you forget to add lucene-backward-codecs.jar?

After adding https://mvnrepository.com/artifact/org.apache.lucene/lucene-backward-codecs/6.6.4 to my classpath the existing index could be read perfectly and my search test worked.

After re-indexing I could remove this jar again, so also this is fine. So it looks like the LuceneSail (with a lucene index) code is working fine.

@jeenbroekstra @barthanssens What is your proposal w.r.t to the new release? Should we just document to re-index after the upgrade? Or should we document to add this jar?

If people have to re-index anyways: would it be an option to migrate straight to lucene 7?

**Comment by jeenbroekstra** [comment]
Heh. I'm not against it, I just wish you had suggested this before I logged all those CQs for Lucene 6 :)

Going straight to Lucene 7 (and I assume Solr 7 as well?) works for me.  We can provide clear instructions on how to either re-index or use a backwards-codec if they come from Lucene 5. 

How does this work out with ElasticSearch?

**Comment by barthanssens** [comment]
@jeenbroekstra 
actually @aschwarte10 did suggested it in the initial question on the mailing list, I suggested to do the upgrades gradually (because versions N can only read indexes from N-1, not N-2, which - only - matters if you're not willing to reindex immediately)

I'm not strongly against going to 7 in one move, just being a bit (too ?) conservative about skipping major versions :)

Maybe @jamesrdf (or someone else working for Ontotext) could offer more info, because IIRC GraphDB uses Lucene as well (+ connectors for Solr / ES ?), but I don't know which version(s)

**Comment by jeenbroekstra** [comment]
@barthanssens AFAIK Ontotext's Lucene support is completely separate from the RDF4J Lucene Sail, so I don't think they have a major opinion on this. But I'll doublecheck :)

**Comment by aschwarte10** [comment]
@jeenbroekstra @barthanssens How about the following approach:

1) We amend the existing PR with one more commit and add "lucene-backwards-compatible" as an optional dependency in the maven POM. This way users are aware that this component is required to read an index created with a previous version.

2) We merge this PR (as at least in my opinion it is in good shape)

3) I will work on a new change that does the upgrade to lucene 7. Whether we use this change for the 2.4 release or later is up to a later decision. As we will need the change anyways at some point in time it probably makes sense to do it.


@jeenbroekstra regarding your elasticsearch question: as far as I understand elasticsearch is always running in an external cluster and the elastic search index of RDF4J only connects to it. So backwards compatibility depends on the elastic search API and is likely independent of the lucene version being used. On https://www.elastic.co/guide/en/elasticsearch/client/java-rest/5.6/java-rest-high-compatibility.html you can find a bit of information regarding compatibility: the recommendation apparently is to have the same API version as the elastic search cluster version. Not sure which elastic search version is currently used in the wild though. Probably the 2.x version that is currently used in RDF4J is no longer widely used as it is pretty old. So in my opinion this could be another reason to directly jump to the latest version.

**Comment by jeenbroekstra** [comment]
@aschwarte10 sounds like a good approach - get the main branch upgraded to v6, and work on an upgrade to v7 in another feature branch, which we can delay until after 2.4 is released if necessary.

**Comment by aschwarte10** [comment]
@jeenbroekstra I added another commit for "lucene-backward-codecs" on the existing POM. In my point of view this is now complete.

In addition, I did the migration to lucene 7 and pushed this to a separate branch in my fork. The change is ontop of the PR branch and the commit can be seen in https://github.com/aschwarte10/rdf4j-storage/commit/27c2b3b61af12469556674ca793ddf71478744a9 

Note that also here we cannot use the latest lucene version (7.2.1 vs 7.3.1) due to elasticsearch. However the change itself looks good so far and tests are passing

We can decide whether we still want to add this to 2.4.0 or a later release. Depending on this I will either create a new issue or use the existing one.

@jeenbroekstra  let me know about the next steps

**Comment by jeenbroekstra** [comment]
Great job @aschwarte10. I've merged your PR now. Happy to close this issue for now. I suggest that you open a new ticket for upgrading to Lucene 7, and we'll see about which release we schedule it for. 

I'm leaving this marked as 'CQ-Pending' until I'm certain all the necessary CQs have been approved.

**Comment by jeenbroekstra** [comment]
Only CQ still under investigation is https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16512, the solrj library. Everything else has been approved.

**Comment by jeenbroekstra** [comment]
Turns out I overlooked a few (transitive) dependencies:

noggit 0.6: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16885
zookeeper 3.4.10
woodstox-core-asl 4.4.1
lucene-backward-codecs 6.6.1

Currently investigating if we can get away with logging (less intrusive) type A CQs (basically only a license compatibility check, fully automated instead of having to have the legal team review manually).
