### ISSUE TITLE
Upgrade Lucene, Solr and elastic search to Lucene 7.x

### ISSUE THREAD

**Issue by aschwarte10** [eclipse/rdf4j-storage#77]
In https://github.com/eclipse/rdf4j-storage/issues/71 we updated lucene and derived modules to Lucene 6.x.

This issue is a follow up to update versions to Lucene 7.x

**Comment by jeenbroekstra** [comment]
@aschwarte10 if I give you a crash course in how the Eclipse review process works, do you think you could take the lead on actually submitting the required CQs for this? I'd rather enjoy it if someone else could do it for once... 

It's not actually hard, just a bit of a drag. For each dependency, and any transitive dependencies that come with that, you'd need to [create a CQ](https://www.eclipse.org/projects/handbook/#pmi-commands-cq) - this is basically just an issue in legal team's bugtracker, IPZilla. The CQ submission tool has some smarts - it will show versions of the library you're trying to add. If our version is already in there, pick that, and it will create a so-called "Piggyback CQ". This is just a record that rdf4j, too, uses this library which has already been approved for another Eclipse project. These CQs typically get approved almost instantly. 

If the version of the library doesn't already exist, you'll need to fill out a short form with the name and a short description (typically just a oneliner), what license it's distributed under, and a link to the project's website and source code repo. The last step is easy to forget: once the CQ issue is created, you should attach the actual source code of the library to the CQ. The easiest way to do this is just to download the source-jar from Maven Central and attach that. 

Things that make this a little easier: 
1. we don't need CQs for patch version bumps of dependencies.
2. we have a couple of "works-with" dependencies, for libraries that we use but don't actually include in our distribution (e.g. elasticsearch-testframework, assertj, and so on). For these kinds of dependencies, you don't need to log any CQs for transitive dependencies (so if assertj depended on, say, log4j, we don't need a CQ for log4j).

The goal of all of this is twofold:
1. we have an accurate of what third-party software we actually include. 
2. we can make a guarantee to our users that our software does not contain any hidden legal nastiness (e.g. stolen code, hidden patented stuff) that could bite them in the behind when they use rdf4j in their own project. 

Anyway, let me know if you want to give it a crack.

**Comment by jeenbroekstra** [comment]
This issue was moved to eclipse/rdf4j#1114
